### ISSUE TITLE
warning/errors on new project startup

### ISSUE THREAD

**Issue by jerash** [bolangi/nama#11]
base on  da194748a
[seijitsu@astrux 8.nama]$ nama -t firstproject
      ////////////////////////////////////////////////////////////////////
     /                                                                  /
    /    Nama multitrack recorder v. 1.111 (c)2008-2014 Joel Roth      /
   /                                                                  /
  /    Audio processing by Ecasound, courtesy of Kai Vehmanen        /
 /                                                                  /
////////////////////////////////////////////////////////////////////

Starting...
Found config file: /home/seijitsu/.namarc
Starting Ecasound server
Creating socket on port 2868.
Starting OSC listener on port 8000
Starting remote control listener on port 57000
Use of uninitialized value $trackname in concatenation (.) or string at /usr/share/perl5/site_perl/Audio/Nama/Project.pm line 48.

project_name: firstproject

Project "firstproject" does not exist.
 Loading project "untitled".
Main: bus name already exists. Skipping.
null: bus name already exists. Skipping.
Setting doodle mode.
Using live inputs only, no duplicate inputs
Exit using 'preview' or 'arm' commands

 No. Name            Status     Source            Destination   Vol   Pan

---

  1  Master          MON        Main bus          1/2           100    50
  2  Mixdown         OFF        --                --             --    --

error caught while generating setup: Undefined subroutine &Audio::Nama::ChainSetup::throw called at /usr/share/perl5/site_perl/Audio/Nama/ChainSetup.pm line 156.

nama untitled Mixdown  ('h' for help)>

the first warning is thrown for a new project, or after saving and reopening.
the second error, is onyl thrown when creating the new project

**Comment by bolangi** [comment]
This bug is not present in v1.216
