### ISSUE TITLE
 error importing wav file with format different from project

### ISSUE THREAD

**Issue by jerash** [bolangi/nama#12]
importing a 44kHz/16bits wav file to a 48kHz project connected to jack

nama crep backing  ('h' for help)> import ~/testaudio/sonita.wav  
WAV file /home/seijitsu/testaudio/sonita.wav has changed! Updating cache.
format: 
s16_le,2,44100
importing /home/seijitsu/testaudio/sonita.wav as /home/seijitsu/8.nama/crep/.wav/backing_1.wav, converting to f32_le,2,48000
caught error: Undefined subroutine &Audio::Nama::teardown_setup called at /usr/share/perl5/site_perl/Audio/Nama/Track.pm line 860.

should nama convert from 44k to 48k ?
converting to 32bits seems useless, as ecasound can take care of this.

**Comment by bolangi** [comment]
The bug causing this error message above is not present in v1.216
